<?php
/**
 * Groups configuration for default Minify implementation
 * @package Minify
 */

/**
 * You may wish to use the Minify URI Builder app to suggest
 * changes. http://yourdomain/min/builder/
 *
 * See http://code.google.com/p/minify/wiki/CustomSource for other ideas
 **/

return array(
    'admin-js'=> array('../../iu-application/views/administration/js/plugins/spinner/ui.spinner.js', '../../iu-application/views/administration/js/plugins/spinner/jquery.mousewheel.js','../../iu-application/views/administration/js/plugins/forms/uniform.js', '../../iu-application/views/administration/js/plugins/forms/jquery.cleditor.js', '../../iu-application/views/administration/js/plugins/forms/jquery.validationEngine-en.js', '../../iu-application/views/administration/js/plugins/forms/jquery.validationEngine.js', '../../iu-application/views/administration/js/plugins/forms/jquery.tagsinput.min.js', '../../iu-application/views/administration/js/plugins/forms/autogrowtextarea.js', '../../iu-application/views/administration/js/plugins/forms/jquery.maskedinput.min.js', '../../iu-application/views/administration/js/plugins/forms/jquery.dualListBox.js', '../../iu-application/views/administration/js/plugins/forms/jquery.inputlimiter.min.js', '../../iu-application/views/administration/js/plugins/forms/chosen.jquery.min.js', '../../iu-application/views/administration/js/plugins/charts/excanvas.min.js', '../../iu-application/views/administration/js/plugins/charts/jquery.flot.js', '../../iu-application/views/administration/js/plugins/charts/jquery.flot.orderBars.js', '../../iu-application/views/administration/js/plugins/charts/jquery.flot.pie.js', '../../iu-application/views/administration/js/plugins/charts/jquery.flot.resize.js', '../../iu-application/views/administration/js/plugins/charts/jquery.sparkline.min.js', '../../iu-application/views/administration/js/plugins/wizard/jquery.form.js', '../../iu-application/views/administration/js/plugins/wizard/jquery.validate.min.js', '../../iu-application/views/administration/js/plugins/wizard/jquery.form.wizard.js', '../../iu-application/views/administration/js/plugins/uploader/plupload.js', '../../iu-application/views/administration/js/plugins/uploader/plupload.html5.js', '../../iu-application/views/administration/js/plugins/uploader/plupload.html4.js', '../../iu-application/views/administration/js/plugins/uploader/jquery.plupload.queue.js', '../../iu-application/views/administration/js/plugins/tables/datatable.js')

	,'admin-js-2'=> array('../../iu-application/views/administration/js/plugins/tables/tablesort.min.js', '../../iu-application/views/administration/js/plugins/tables/resizable.min.js', '../../iu-application/views/administration/js/plugins/ui/jquery.tipsy.js', '../../iu-application/views/administration/js/plugins/ui/jquery.collapsible.min.js', '../../iu-application/views/administration/js/plugins/ui/jquery.prettyPhoto.js', '../../iu-application/views/administration/js/plugins/ui/jquery.progress.js', '../../iu-application/views/administration/js/plugins/ui/jquery.timeentry.min.js', '../../iu-application/views/administration/js/plugins/ui/jquery.colorpicker.js', '../../iu-application/views/administration/js/plugins/ui/jquery.jgrowl.js','../../iu-application/views/administration/js/plugins/ui/jquery.breadcrumbs.js', '../../iu-application/views/administration/js/plugins/ui/jquery.sourcerer.js', '../../iu-application/views/administration/js/plugins/calendar.min.js', '../../iu-application/views/administration/js/base64.js', '../../iu-application/views/administration/elfinder/js/elfinder.min.js', '../../iu-application/views/administration/js/jquery.msgbox.min.js', '../../iu-application/views/administration/js/jqueryFileTree.js', '../../iu-application/views/administration/js/jquery.easing.1.3.js', '../../iu-application/views/administration/js/codemirror.js', '../../iu-application/views/administration/js/highlighters/clike.js', '../../iu-application/views/administration/js/highlighters/xml.js', '../../iu-application/views/administration/js/highlighters/javascript.js', '../../iu-application/views/administration/js/highlighters/css.js', '../../iu-application/views/administration/js/highlighters/php.js', '../../iu-application/views/administration/js/jquery.sparkline.js', '../../iu-application/views/administration/js/uploadify/jquery.uploadify.min.js', '../../iu-application/views/administration/js/custom.js')

    ,'admin-css'=> array('../../iu-application/views/administration/css/main.css', '../../iu-application/views/administration/css/stickymenu.css', '../../iu-application/views/administration/elfinder/css/elfinder.min.css', '../../iu-application/views/administration/elfinder/css/theme.css', '../../iu-application/views/administration/css/jquery.msgbox.css', '../../iu-application/views/administration/css/jqueryFileTree.css', '../../iu-application/views/administration/css/codemirror.css','../lightbox/css/jackbox.css')

	,'base-js'=> array('../js/phpjs.js', '../js/functions.js', '../js/webfont.js', '../js/jquery.scrollTo.min.js')

	,'user-js'=> array('../js/jquery.jgrowl.min.js', '../icoroll/icoroll.js', '../js/instant.js')

	,'base-css'=> array('../css/jquery.jgrowl.css', '../icoroll/icoroll.css', '../icoroll/dark.css', '../css/style.css')
);